import Head from 'next/head'
import Navbar from '../components/Navbar'
import Hero from '../components/Hero'
import FeatureSection from '../components/FeatureSection'
import ComingSoon from '../components/ComingSoon'
import Footer from '../components/Footer'

// Feature icon SVGs
const ImageIcon = (
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true" className="w-7 h-7 text-emerald-50">
    <path fillRule="evenodd" d="M1.5 6a2.25 2.25 0 012.25-2.25h16.5A2.25 2.25 0 0122.5 6v12a2.25 2.25 0 01-2.25 2.25H3.75A2.25 2.25 0 011.5 18V6zM3 16.06V18c0 .414.336.75.75.75h16.5A.75.75 0 0021 18v-1.94l-2.69-2.689a1.5 1.5 0 00-2.12 0l-.88.879.97.97a.75.75 0 11-1.06 1.06l-5.16-5.159a1.5 1.5 0 00-2.12 0L3 16.061zm10.125-7.81a1.125 1.125 0 112.25 0 1.125 1.125 0 01-2.25 0z" clipRule="evenodd" />
  </svg>
)

const DownloadIcon = (
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true" className="w-7 h-7 text-emerald-50">
    <path d="M3.375 3C2.339 3 1.5 3.84 1.5 4.875v.75c0 1.036.84 1.875 1.875 1.875h17.25c1.035 0 1.875-.84 1.875-1.875v-.75C22.5 3.839 21.66 3 20.625 3H3.375z" />
    <path fillRule="evenodd" d="M3.087 9l.54 9.176A3 3 0 006.62 21h10.757a3 3 0 002.995-2.824L20.913 9H3.087zM12 10.5a.75.75 0 01.75.75v4.94l1.72-1.72a.75.75 0 111.06 1.06l-3 3a.75.75 0 01-1.06 0l-3-3a.75.75 0 111.06-1.06l1.72 1.72v-4.94a.75.75 0 01.75-.75z" clipRule="evenodd" />
  </svg>
)

const CursorIcon = (
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true" className="w-7 h-7 text-emerald-50">
    <path fillRule="evenodd" d="M12 1.5a.75.75 0 01.75.75V4.5a.75.75 0 01-1.5 0V2.25A.75.75 0 0112 1.5zM5.636 4.136a.75.75 0 011.06 0l1.592 1.591a.75.75 0 01-1.061 1.06l-1.591-1.59a.75.75 0 010-1.061zm12.728 0a.75.75 0 010 1.06l-1.591 1.592a.75.75 0 01-1.06-1.061l1.59-1.591a.75.75 0 011.061 0zm-6.816 4.496a.75.75 0 01.82.311l5.228 7.917a.75.75 0 01-.777 1.148l-2.097-.43 1.045 3.9a.75.75 0 01-1.45.388l-1.044-3.899-1.601 1.42a.75.75 0 01-1.247-.606l.569-9.47a.75.75 0 01.554-.68zM3 10.5a.75.75 0 01.75-.75H6a.75.75 0 010 1.5H3.75A.75.75 0 013 10.5zm14.25 0a.75.75 0 01.75-.75h2.25a.75.75 0 010 1.5H18a.75.75 0 01-.75-.75zm-8.962 3.712a.75.75 0 010 1.061l-1.591 1.591a.75.75 0 11-1.061-1.06l1.591-1.592a.75.75 0 011.06 0z" clipRule="evenodd" />
  </svg>
)

const DocumentIcon = (
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true" className="w-7 h-7 text-emerald-50">
    <path fillRule="evenodd" d="M5.625 1.5c-1.036 0-1.875.84-1.875 1.875v17.25c0 1.035.84 1.875 1.875 1.875h12.75c1.035 0 1.875-.84 1.875-1.875V12.75A3.75 3.75 0 0016.5 9h-1.875a1.875 1.875 0 01-1.875-1.875V5.25A3.75 3.75 0 009 1.5H5.625zM7.5 15a.75.75 0 01.75-.75h7.5a.75.75 0 010 1.5h-7.5A.75.75 0 017.5 15zm.75 2.25a.75.75 0 000 1.5H12a.75.75 0 000-1.5H8.25z" clipRule="evenodd" />
    <path d="M12.971 1.816A5.23 5.23 0 0114.25 5.25v1.875c0 .207.168.375.375.375H16.5a5.23 5.23 0 013.434 1.279 9.768 9.768 0 00-6.963-6.963z" />
  </svg>
)

const ShareIcon = (
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true" className="w-7 h-7 text-emerald-50">
    <path fillRule="evenodd" d="M15.75 4.5a3 3 0 11.825 2.066l-8.421 4.679a3.002 3.002 0 010 1.51l8.421 4.679a3 3 0 11-.729 1.31l-8.421-4.678a3 3 0 110-4.132l8.421-4.679a3 3 0 01-.096-.755z" clipRule="evenodd" />
  </svg>
)

const StackIcon = (
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true" className="w-7 h-7 text-emerald-50">
    <path d="M5.566 4.657A4.505 4.505 0 016.75 4.5h10.5c.41 0 .806.055 1.183.157A3 3 0 0015.75 3h-7.5a3 3 0 00-2.684 1.657zM2.25 12a3 3 0 013-3h13.5a3 3 0 013 3v6a3 3 0 01-3 3H5.25a3 3 0 01-3-3v-6zM5.25 7.5c-.41 0-.806.055-1.184.157A3 3 0 016.75 6h10.5a3 3 0 012.683 1.657A4.505 4.505 0 0018.75 7.5H5.25z" />
  </svg>
)

const featureSections = [
  {
    title: 'Manage all creations in one place',
    description: 'You can use ChatGPT Finder to manage all your creations in one place. You can also use it to find your creations by conversation or download all your creations at once.',
    image: '/img/download-all-files.jpg',
    imageAlt: 'ChatGPT Finder - Manage all your ChatGPT creations like magic',
    reversed: false,
    features: [
      {
        icon: ImageIcon,
        title: 'View all creations by conversation',
        description: 'Explore all creations in unified and beautiful interface. Including images generated by DALL-E 3, code file generated by Code analysis tool, and more.',
      },
      {
        icon: DownloadIcon,
        title: 'Download all creations conveniently',
        description: 'Download creations related files by conversation or all at once.',
      },
      {
        icon: CursorIcon,
        title: 'All in ChatGPT',
        description: 'Use ChatGPT Finder just in ChatGPT via browser extension.',
      },
    ],
  },
  {
    title: 'Explore and share all DALL-E 3 prompts',
    description: 'You can use ChatGPT Finder to manage all your DALL-E 3 prompts in one place, either copy one or download all at once.',
    image: '/img/creations-view.jpg',
    imageAlt: 'ChatGPT Finder - Explore and share all DALL-E 3 prompts',
    reversed: true,
    features: [
      {
        icon: DocumentIcon,
        title: 'Explore all DALL-E 3 prompts',
        description: 'Explore and share all original DALL-E 3 prompts generated by ChatGPT in unified and beautiful interface.',
      },
      {
        icon: ShareIcon,
        title: 'Share DALL-E 3 prompts by one click',
        description: 'You can copy the prompt you like one by one or download all prompts at once.',
      },
    ],
  },
  {
    title: 'Download specific creations',
    description: 'You can use ChatGPT Finder to download creations of specific conversation.',
    image: '/img/download-conversation-content-large.jpg',
    imageAlt: 'ChatGPT Finder - Download creations whatever you want',
    reversed: false,
    features: [
      {
        icon: DownloadIcon,
        title: 'Download specific conversation content by one click',
        description: 'You can download interest conversation content by one click.',
      },
      {
        icon: StackIcon,
        title: 'All download task happens in background',
        description: 'Multiple download tasks can happen in background, convenient and fast.',
      },
    ],
  },
]

export default function Home() {
  return (
    <>
      <Head>
        <title>ChatGPT Finder - Manage all your ChatGPT creations like magic</title>

      </Head>
      <Navbar />
      <Hero />
      {featureSections.map((section, index) => (
        <FeatureSection key={index} {...section} />
      ))}
      <ComingSoon />
      <Footer />
    </>
  )
}
